export const SEO_CITIES: Record<string, { name: string; region: string }> = {
  london: { name: 'London', region: 'Greater London' },
  manchester: { name: 'Manchester', region: 'Greater Manchester' },
  birmingham: { name: 'Birmingham', region: 'West Midlands' },
  leeds: { name: 'Leeds', region: 'West Yorkshire' },
  glasgow: { name: 'Glasgow', region: 'Scotland' },
  edinburgh: { name: 'Edinburgh', region: 'Scotland' },
  bristol: { name: 'Bristol', region: 'South West England' },
  liverpool: { name: 'Liverpool', region: 'Merseyside' },
  sheffield: { name: 'Sheffield', region: 'South Yorkshire' },
  cardiff: { name: 'Cardiff', region: 'Wales' },
  nottingham: { name: 'Nottingham', region: 'East Midlands' },
  newcastle: { name: 'Newcastle', region: 'Tyne and Wear' },
  brighton: { name: 'Brighton', region: 'East Sussex' },
  leicester: { name: 'Leicester', region: 'Leicestershire' },
  oxford: { name: 'Oxford', region: 'Oxfordshire' },
  cambridge: { name: 'Cambridge', region: 'Cambridgeshire' },
  york: { name: 'York', region: 'North Yorkshire' },
  bath: { name: 'Bath', region: 'Somerset' },
  reading: { name: 'Reading', region: 'Berkshire' },
  southampton: { name: 'Southampton', region: 'Hampshire' },
  belfast: { name: 'Belfast', region: 'Northern Ireland' },
  coventry: { name: 'Coventry', region: 'West Midlands' },
  aberdeen: { name: 'Aberdeen', region: 'Scotland' },
  dundee: { name: 'Dundee', region: 'Scotland' },
  swansea: { name: 'Swansea', region: 'Wales' },
}

export const SEO_SECTORS: Record<string, { name: string; keywords: string }> = {
  'accountancy-finance': { name: 'Accountancy & Finance', keywords: 'accountancy jobs, finance jobs, accounting careers' },
  'business-management': { name: 'Business & Management', keywords: 'business jobs, management jobs, business manager' },
  'charity': { name: 'Charity', keywords: 'charity jobs, nonprofit jobs, charity sector careers' },
  'creative-design': { name: 'Creative & Design', keywords: 'creative jobs, design jobs, graphic designer' },
  'digital-it': { name: 'Digital & IT', keywords: 'IT jobs, tech jobs, software developer, digital jobs' },
  'energy-utilities': { name: 'Energy & Utilities', keywords: 'energy jobs, utilities jobs, renewable energy' },
  'engineering': { name: 'Engineering', keywords: 'engineering jobs, engineer careers, mechanical engineer' },
  'environment-agriculture': { name: 'Environment & Agriculture', keywords: 'environment jobs, agriculture jobs, farming' },
  'healthcare': { name: 'Healthcare', keywords: 'healthcare jobs, NHS jobs, nursing jobs, medical' },
  'hospitality-tourism': { name: 'Hospitality & Tourism', keywords: 'hospitality jobs, hotel jobs, restaurant jobs, chef jobs' },
  'law-legal': { name: 'Law & Legal', keywords: 'legal jobs, law jobs, solicitor, paralegal' },
  'marketing-pr': { name: 'Marketing & PR', keywords: 'marketing jobs, PR jobs, digital marketing' },
  'media': { name: 'Media', keywords: 'media jobs, journalism, broadcasting, content creator' },
  'property-construction': { name: 'Property & Construction', keywords: 'construction jobs, property jobs, building' },
  'public-services': { name: 'Public Services', keywords: 'public sector jobs, government jobs, civil service' },
  'recruitment-hr': { name: 'Recruitment & HR', keywords: 'HR jobs, recruitment jobs, human resources' },
  'retail-sales': { name: 'Retail & Sales', keywords: 'retail jobs, sales jobs, shop assistant, sales manager' },
  'science': { name: 'Science', keywords: 'science jobs, research jobs, laboratory, scientist' },
  'teaching-education': { name: 'Teaching & Education', keywords: 'teaching jobs, education jobs, teacher, lecturer' },
  'transport-logistics': { name: 'Transport & Logistics', keywords: 'transport jobs, logistics jobs, driver, warehouse' },
}
