// Comprehensive list of UK cities, towns, and London areas
// Used for autocomplete in the job search location field

export const ukCities: string[] = [
  // London areas
  'London',
  'Central London',
  'City of London',
  'West End',
  'Shoreditch',
  'Mayfair',
  'Canary Wharf',
  'Soho',
  'Westminster',
  'Covent Garden',
  'Kensington',
  'Chelsea',
  'Camden',
  'Brixton',
  'Hackney',
  'Islington',
  'Notting Hill',
  'Fitzrovia',
  'Marylebone',
  'Knightsbridge',
  'Fulham',
  'Battersea',
  'Clapham',
  'Dalston',
  'Peckham',
  'Bermondsey',
  'Stratford',
  'Greenwich',
  'Wimbledon',
  'Richmond',
  'Hammersmith',
  'Ealing',
  'Croydon',
  'Brixton',
  'Putney',
  'Wandsworth',
  'Tooting',
  'Balham',
  'Angel',
  'Kings Cross',
  'Paddington',
  'Victoria',
  'Clerkenwell',
  'Farringdon',
  'Elephant and Castle',

  // Major English cities
  'Manchester',
  'Birmingham',
  'Leeds',
  'Liverpool',
  'Bristol',
  'Newcastle upon Tyne',
  'Sheffield',
  'Nottingham',
  'Southampton',
  'Brighton',
  'Oxford',
  'Cambridge',
  'Bath',
  'York',
  'Reading',
  'Leicester',
  'Coventry',
  'Bournemouth',
  'Exeter',
  'Norwich',
  'Plymouth',
  'Cheltenham',
  'Guildford',
  'Windsor',
  'Milton Keynes',
  'Northampton',
  'Peterborough',
  'Ipswich',
  'Canterbury',
  'Chester',
  'Derby',
  'Wolverhampton',
  'Stoke-on-Trent',
  'Sunderland',
  'Bradford',
  'Hull',
  'Middlesbrough',
  'Blackpool',
  'Luton',
  'Watford',
  'Harrogate',
  'Stratford-upon-Avon',
  'Colchester',
  'Worcester',
  'Salisbury',
  'Lincoln',
  'Carlisle',
  'Lancaster',
  'Durham',
  'Hereford',
  'Gloucester',
  'Chelmsford',
  'Maidstone',
  'Tunbridge Wells',
  'Hastings',
  'Eastbourne',
  'Worthing',
  'Basingstoke',
  'Winchester',
  'Portsmouth',
  'Poole',
  'Torquay',
  'Taunton',
  'Swindon',
  'Warwick',
  'Leamington Spa',
  'St Albans',
  'High Wycombe',
  'Slough',
  'Maidenhead',
  'Margate',
  'Folkestone',
  'Dover',
  'Scarborough',
  'Whitby',
  'Harrow',
  'Enfield',
  'Bromley',
  'Sutton',
  'Kingston upon Thames',
  'Barnet',
  'Brentwood',
  'Romford',
  'Ilford',
  'Wembley',
  'Uxbridge',
  'Epsom',
  'Woking',
  'Crawley',
  'Horsham',
  'Chichester',
  'Aylesbury',
  'Banbury',
  'Newbury',
  'Andover',
  'Farnham',
  'Reigate',
  'Dorking',
  'Redhill',
  'Sevenoaks',
  'Tonbridge',
  'Ashford',
  'Deal',
  'Whitstable',
  'Broadstairs',
  'Ramsgate',
  'Burnley',
  'Blackburn',
  'Bolton',
  'Bury',
  'Rochdale',
  'Oldham',
  'Stockport',
  'Wigan',
  'Warrington',
  'Salford',
  'Trafford',
  'Preston',
  'Accrington',
  'Chorley',
  'Morecambe',
  'Barnsley',
  'Rotherham',
  'Doncaster',
  'Wakefield',
  'Huddersfield',
  'Halifax',
  'Dewsbury',
  'Keighley',
  'Skipton',
  'Harrogate',
  'Ripon',
  'Grimsby',
  'Scunthorpe',
  'Mansfield',
  'Newark',
  'Grantham',
  'Loughborough',
  'Hinckley',
  'Corby',
  'Kettering',
  'Wellingborough',
  'Rugby',
  'Nuneaton',
  'Tamworth',
  'Stafford',
  'Burton upon Trent',
  'Lichfield',
  'Cannock',
  'Walsall',
  'Dudley',
  'West Bromwich',
  'Solihull',
  'Redditch',
  'Kidderminster',
  'Telford',
  'Shrewsbury',
  'Oswestry',
  'Hereford',
  'Great Malvern',
  'Evesham',
  'Stroud',
  'Cirencester',
  'Chippenham',
  'Devizes',
  'Trowbridge',
  'Frome',
  'Yeovil',
  'Bridgwater',
  'Weston-super-Mare',
  'Clevedon',
  'Barnstaple',
  'Bideford',
  'Truro',
  'Falmouth',
  'Penzance',
  'Newquay',
  'St Ives',
  'Weymouth',
  'Dorchester',
  'Blandford Forum',
  'Christchurch',
  'Lymington',
  'Fareham',
  'Gosport',
  'Havant',
  'Petersfield',
  'Aldershot',
  'Fleet',
  'Camberley',
  'Bracknell',
  'Wokingham',

  // Scotland
  'Edinburgh',
  'Glasgow',
  'Aberdeen',
  'Dundee',
  'Inverness',
  'Stirling',
  'Perth',
  'St Andrews',
  'Fort William',
  'Oban',
  'Ayr',
  'Kilmarnock',
  'Dumfries',
  'Paisley',
  'East Kilbride',
  'Livingston',
  'Falkirk',
  'Dunfermline',
  'Kirkcaldy',

  // Wales
  'Cardiff',
  'Swansea',
  'Newport',
  'Wrexham',
  'Bangor',
  'Aberystwyth',
  'Carmarthen',
  'Llandudno',
  'Tenby',
  'Brecon',
  'Caernarfon',
  'Rhyl',
  'Colwyn Bay',
  'Barry',
  'Bridgend',
  'Neath',
  'Port Talbot',
  'Merthyr Tydfil',
  'Pontypridd',
  'Cwmbran',

  // Northern Ireland
  'Belfast',
  'Derry',
  'Lisburn',
  'Newry',
  'Bangor',
  'Armagh',
  'Omagh',
  'Enniskillen',
  'Coleraine',
  'Ballymena',
  'Larne',
  'Cookstown',
  'Craigavon',
  'Carrickfergus',
  'Newtownabbey',
]
